
const separators = ` 　\t&＆:：\/／・、；,`;
const roles = [
  'Custom',
  'custom',
  'Music',
  'music',
  'Composition',
  'composition',
  'Composer',
  'composer',
  'Compose',
  'compose',
  'Composed',
  'composed',
  'Composed by',
  'composed by',
  'Composed By',
  'Lyrics',
  'lyrics',
  'Lyricist',
  'lyricist',
  'Lyricists',
  'lyricists',
  'Lyric',
  'lyric',
  'Arrangement',
  'arrangement',
  'Arranger',
  'arranger',
  'Arrange',
  'arrange',
  'Arranged',
  'arranged',
  'Arranged by',
  'arranged by',
  'Arranged By',
  'Vocalist',
  'vocalist',
  'Vocalists',
  'vocalists',
  'Vocal',
  'vocal',
  'Vocals',
  'vocals',
  'Performer',
  'performer',
  'Featured',
  'Featuring',
  'featured',
  'featuring',
  'Jacket Illustration',
  'Jacket illustration',
  'jacket illustration',
  'Illustration',
  'illustration',
  'Illustrator',
  'illustrator',
  'Illust',
  'illust',
  'Label',
  'label',
  'Circle',
  'circle',
  'Producer',
  'producer',
  'Produced',
  'produced',
  'produced by',
  'Recording',
  'recording',
  'Recording studio',
  'recording studio',
  'Recording Studio',
  'Recording studios',
  'recording studios',
  'Recording Studios',
  'Recording engineer',
  'recording engineer',
  'Recording Engineer',
  'Recording engineers',
  'recording engineers',
  'Recording Engineers',
  'Recorded',
  'recorded',
  'Recorded studio',
  'recorded studio',
  'Recorded Studio',
  'Recorded studios',
  'recorded studios',
  'Recorded Studios',
  'Recorded engineer',
  'recorded engineer',
  'Recorded Engineer',
  'Recorded engineers',
  'recorded engineers',
  'Recorded Engineers',
  'Recorded by',
  'recorded by',
  'Recorded By',
  'Recorded at',
  'recorded at',
  'Recorded At',
  'Recorded in',
  'recorded in',
  'Recorded In',
  'Guest Vocal',
  'Guest vocal',
  'guest vocal',
  'Guest Vocals',
  'Guest vocals',
  'guest vocals',
  'Chorus',
  'chorus',
  'Choir',
  'choir',
  'Narrated',
  'narrated',
  'narrater',
  'Narrater',
  'Narration',
  'narration',
  'Narrations',
  'narrations',
  'Storyteller',
  'storyteller',
  'vocal edit',
  'Vocal edit',
  'Vocal Edit',
  'vocal edition',
  'Vocal edition',
  'Vocal Edition',
  'vocal edited',
  'Vocal edited',
  'Vocal Edited',
  'vocal editor',
  'Vocal Editor',
  'Vocal editor',
  'vocal direct',
  'Vocal direct',
  'Vocal Direct',
  'vocal director',
  'Vocal director',
  'Vocal Director',
  'vocal direction',
  'Vocal direction',
  'Vocal Direction',
  'sound direct',
  'sound direction',
  'sound director',
  'Sound direct',
  'Sound direction',
  'Sound director',
  'Sound Direct',
  'Sound Direction',
  'Sound Director',
  'Mixing',
  'mixing',
  'Mixing studio',
  'mixing studio',
  'Mixing Studio',
  'Mixing studios',
  'mixing studios',
  'Mixing Studios',
  'Mixing engineer',
  'mixing engineer',
  'Mixing Engineer',
  'Mixing engineers',
  'mixing engineers',
  'Mixing Engineers',
  'Mixed',
  'mixed',
  'Mixed studio',
  'mixed studio',
  'Mixed Studio',
  'Mixed studios',
  'mixed studios',
  'Mixed Studios',
  'Mixed engineer',
  'mixed engineer',
  'Mixed Engineer',
  'Mixed engineers',
  'mixed engineers',
  'Mixed Engineers',
  'Mixed by',
  'mixed by',
  'Mixed By',
  'Mixed at',
  'mixed at',
  'Mixed At',
  'Mixed in',
  'mixed in',
  'Mixed In',
  'Mastering',
  'mastering',
  'Mastering engineer',
  'mastering engineer',
  'Mastering Engineer',
  'Mastering engineers',
  'mastering engineers',
  'Mastering Engineers',
  'Mastering studio',
  'mastering studio',
  'Mastering Studio',
  'Mastering studios',
  'mastering studios',
  'Mastering Studios',
  'Mastered',
  'mastered',
  'Mastered engineer',
  'mastered engineer',
  'Mastered Engineer',
  'Mastered engineers',
  'mastered engineers',
  'Mastered Engineers',
  'Mastered studio',
  'mastered studio',
  'Mastered Studio',
  'Mastered studios',
  'mastered studios',
  'Mastered Studios',
  'Mastered at',
  'mastered at',
  'Mastered At',
  'design',
  'Design',
  'designer',
  'Designer',
  'ボーカル',
  'アレンジ',
  'イラスト',
  'レーベル',
  'マスタリング',
  'フューチャリング',
  'デザイン',
  'オールデザイン',
  'でざいん',
  'コーラス',
  'こーらす',
  'クワイア',
  'ナレーション',
  'ナレーター',
  'ナレータ',
  'ボイスエディット',
  'ウォイスエディット',
  'ヴォイスエディティング',
  'ボイスエディター',
  'サウンドディレクト',
  'サウンドディレクション',
  'サウンドデレクション',
  '音響監督',
  '艺术家',
  '歌唱',
  '作詞作編曲',
  '作词作编曲',
  '作詞作曲',
  '作词作曲',
  '作詞曲',
  '作词曲',
  '作編曲',
  '作编曲',
  '作曲',
  '編曲',
  '编曲',
  '作詞',
  '作词',
  '厂牌',
  '脚本',
  '插图',
  '插画',
  '绘画',
  '制作人',
  '出版方',
  '录音',
  '原作',
  '声乐',
  '客串',
  '乐器',
  '和声',
  '合唱',
  '念白',
  '旁白',
  '混音',
  '母带制作',
  '母带',
  '设计',
  '音响监督',
  '人声编辑',
  '人声指导',
];

module.exports = grammar({
  name: 'rkgk',
  extras: _ => [/[\s　]/],

  rules: {
    source_file: $ => seq(
      optional(alias($.credit_block_maybeparts, $.credit_block)),
      choice(
        repeat1($.disc),
        $._disc,
      ),
    ),

    disc: $ => seq(
      'DISC',
      '\n',
      $._disc,
    ),
    _disc: $ => repeat1($.song),

    song: $ => seq(
      $._quotable_song_title_maybecomment,
      optional($.credit_block),
    ),

    credit_block_maybeparts: $ => prec(-1, repeat1(alias($.credit_field_maybeparts, $.credit_field))),
    credit_field_maybeparts: $ => prec.left(seq(
      repeat1(seq(
        $.role,
        $._sep,
      )),
      $._quotable_creator_field_maybeparts,
      repeat(seq(
        field('creatorSeparator', alias($._sep, $.creator_sep)),
        $._quotable_creator_field_maybeparts,
      )),
      choice($._sep, '\n', seq($._sep, '\n'), seq($._sep, '\n', $._sep))
    )),
    credit_block: $ => prec(-1, repeat1($.credit_field)),
    credit_field: $ => prec.left(seq(
      repeat1(seq(
        $.role,
        $._sep,
      )),
      $._quotable_creator_field,
      repeat(seq(
        field('creatorSeparator', alias($._sep, $.creator_sep)),
        $._quotable_creator_field,
      )),
      optional(choice($._sep, '\n', seq($._sep, '\n'), seq($._sep, '\n', $._sep)))
    )),

    _quotable_song_title_maybecomment: $ => prec.right(seq(
      $._quotable_song_title,
      optional('\n'),
      optional(choice(
        seq(
          '//',
          alias(/[^\n]+/, $.comment),
        ),
        alias(token(seq('原曲', /[^\n]+/)), $.comment),
      )),
    )),
    _quotable_song_title: $ => choice(
      seq('《', field('title', $.song_title), '》'),  // quoting
      field('title', $.song_title),
    ),
    song_title: _ => prec.right(repeat1(
      // lexically, creator_name > song_title
      token(prec(-1, /[^\n]/))
    )),

    _quotable_creator_field_maybeparts: $ => choice(
      seq($._quotable_creator_field, optional($.parts)),
      $.parts,
    ),

    _quotable_creator_field: $ => seq(
      $._quotable_creator_name,
      optional(choice(
        // CAVEAT: this lexical precedence will lead to "implicit space > _seq" for cases like "name (circle..."
        seq(alias(token(prec(1, /[(（]CV[：:.]/)), $.cv_conj), $._quotable_creator_name, alias(/[)）]/, $.cv_conj)),
        seq(alias(/[|｜]/, $.cv_conj), $._quotable_creator_name),
      )),
    ),

    _quotable_creator_name: $ => choice(
      // lexically, 《creator_name》 > 《song_title》
      seq(token(prec(1, '《')), field('creator', alias(/[^》\n]+/, $.creator_name)), '》'),  // quoting
      field('creator', $.creator_name),
    ),
    creator_name: _ => prec.right(repeat1(
      // lexically, creator_name > song_title
      token(prec(0, new RegExp(`[^${separators}《》\n]`)))
    )),

    role: $ => choice(
      $._role_instrument,
      $._role_custom,
      $._role,
    ),
    _role_instrument: _ => token(prec(1, new RegExp(`(乐器|设计|插图)-([^${separators}]| )+`))),
    _role_custom: _ => token(prec(1, new RegExp(`custom-([^${separators}]| )+`))),
    _role: _ => choice(...roles.map(r => field('role', r))),

    parts: _ => /\((Tr|tr|M|m)?\.? ?[0-9,-. ]+\)/,

    _sep: _ => token(new RegExp(`[${separators}]+`)),
  }
});
