/// File generated by script/genMetaTag.ts

export interface MetaTagKind {
    [key: string]: MetaTagClass;
}
export interface MetaTagClass {
    tags: string[];
    index: number;
}

export const SUBJECT_TYPE: Record<number, string> = {
    1: '书籍',
    2: '动画',
    3: '音乐',
    4: '游戏',
    6: '三次元',
}


const 书籍: MetaTagKind = {
    分类: {
        tags: ['漫画', '小说', '系列', '短篇', '画集', '短篇集', '公式书', '写真集', '绘本', '杂志', 'TRPG', '剧本'],
        index: 10000,
    },
    来源: {
        tags: ['游戏改', '原创', '小说改', '动画改', '漫画改', '影视改'],
        index: 10003,
    },
    题材: {
        tags: ['推理', '后宫', '科幻', '百合', '恐怖', '恋爱', '音乐', '爱情', '校园', '穿越', '战斗', '运动', '游戏', '武侠', '现实', '奇幻', '惊悚', '搞笑', '日常', '悬疑', '剧情', '冒险', '异世界', '历史', '军事', '乙女', '美食', '职场', '玄幻', '机战', '都市', '仙侠', '无限'],
        index: 10004,
    },
    受众: {
        tags: ['少年', '少女', '青年', 'BL', '一般向', 'GL', '名著', '儿童', '女性', 'TL', '无cp'],
        index: 10004,
    },
    地区: {
        tags: ['日本', '中国', '韩国', '台湾', '美国', '法国', '泰国', '香港', '马来西亚'],
        index: 10005,
    },
    分级: {
        tags: ['R18'],
        index: 10006,
    },
    进度: {
        tags: ['已完结', '连载中', '停载'],
        index: 10007,
    },
    媒介: {
        tags: ['同人志', '单行本', '特典', 'MOOK', '电子书', '纸质书', '电子单话', '限定流通'],
        index: 11000,
    },
}

const 动画: MetaTagKind = {
    分类: {
        tags: ['短片', '剧场版', 'TV', 'OVA', 'MV', 'CM', 'WEB', 'PV', '动态漫画'],
        index: 21000,
    },
    来源: {
        tags: ['原创', '漫画改', '游戏改', '小说改', '动画改', '影视改'],
        index: 23000,
    },
    类型: {
        tags: ['科幻', '喜剧', '同人', '百合', '校园', '惊悚', '后宫', '机战', '悬疑', '恋爱', '奇幻', '推理', '运动', '耽美', '音乐', '战斗', '冒险', '萌系', '穿越', '玄幻', '乙女', '恐怖', '历史', '日常', '剧情', '武侠', '短片集', '美食', '职场'],
        index: 24000,
    },
    地区: {
        tags: ['日本', '欧美', '中国', '美国', '韩国', '法国', '英国', '香港', '俄罗斯', '苏联', '捷克', '台湾', '马来西亚'],
        index: 25000,
    },
    分级: {
        tags: ['R18'],
        index: 26000,
    },
    受众: {
        tags: ['BL', 'GL', '子供向', '女性向', '少女向', '少年向', '青年向', '无cp'],
        index: 28000,
    },
}

const 音乐: MetaTagKind = {
    分类: {
        tags: ['专辑', 'ASMR'],
        index: 30000,
    },
    类型: {
        tags: ['OST', '同人音乐', 'ED', 'OP', '角色歌', 'Vocaloid', 'Drama', 'Remix', 'IN', '印象曲', 'VOCAL', 'Radio', 'Arrange', '单曲', '精选集', 'TM', '朗读剧', '艺人专辑'],
        index: 30001,
    },
    来源: {
        tags: ['动画', '游戏', '原创', '电影', '小说', '电视剧', '漫画', '有声作品'],
        index: 30002,
    },
    受众: {
        tags: ['BL', '乙女', 'TL'],
        index: 30003,
    },
    地区: {
        tags: ['日本', '韩国', '欧美', '中国'],
        index: 30004,
    },
    风格: {
        tags: ['JPOP', '古典', '摇滚', 'trance', '电子', 'hardcore', 'Techno'],
        index: 30005,
    },
    分级: {
        tags: ['R18', '全0'],
        index: 30007,
    },
    介质: {
        tags: ['CD', '8cm', 'DVD', 'Digital', '磁带', '黑胶'],
        index: 30008,
    },
}

const 游戏: MetaTagKind = {
    分类: {
        tags: ['游戏', 'mod', '桌游', 'DLC', '周边', '合集', '扩展包', '改版', '软件'],
        index: 41000,
    },
    平台: {
        tags: ['PC', 'Web', 'Windows', 'Mac', 'Linux', 'PS5', 'XSX', 'NS', 'NS2', 'iOS', 'Android', 'VR', 'PSVR2', '街机', 'XboxOne', 'Xbox', 'Xbox360', 'Wii', 'WiiU', 'NDS', 'FC', 'GBA', '3DS', 'GBC', 'GB', 'N64', 'NGC', 'SFC', 'PS4', 'PSVR', 'PSV', 'PS3', 'PSP', 'PS2', 'PS', 'DC', 'MD', 'SS', 'DOS', 'PCE', 'AppleII', 'Amiga', 'PC98', 'X68000', 'PC88', 'Symbian'],
        index: 42000,
    },
    类型: {
        tags: ['AAVG', 'ACT', 'ADV', 'ARPG', 'AVG', 'CCG', 'CRPG', 'DBG', 'DRPG', 'EDU', 'FPS', 'FTG', 'Fly', 'Horror', 'JRPG', 'MMORPG', 'MOBA', 'MUG', 'PUZ', 'Platform', 'RAC', 'RPG', 'RTS', 'RTT', 'Rhythm', 'Roguelike', 'SIM', 'SLG', 'SPG', 'SRPG', 'STG', 'Sandbox', 'Strategy', 'Survival', 'TAB', 'TBS', 'TBT', 'TCG', 'TPS', 'VN', '休闲'],
        index: 43000,
    },
    受众: {
        tags: ['Galgame', '同人', 'BL', '乙女', 'GL'],
        index: 44000,
    },
    分级: {
        tags: ['全年龄', 'R18'],
        index: 45000,
    },
}

const 三次元: MetaTagKind = {
    分类: {
        tags: ['电视剧', '电影', '综艺', '短剧', '电台', '广播剧', '演出', '有声剧', '有声书'],
        index: 60000,
    },
    来源: {
        tags: ['小说改', '游戏改', '漫画改', '原创', '动画改', '影视改'],
        index: 60002,
    },
    题材: {
        tags: ['犯罪', '悬疑', '推理', '喜剧', '爱情', '特摄', '科幻', '音乐', '校园', '美食', '奇幻', '动作', '家庭', '战争', '玄幻', '西部', '歌舞', '历史', '传记', '剧情', '纪录片', '恐怖', '惊悚', '职场', '武侠', '古装', '布袋戏', '灾难', '冒险', '少儿', '运动', '同性', '选集剧'],
        index: 60004,
    },
    地区: {
        tags: ['日本', '欧美', '美国', '中国', '华语', '英国', '韩国', '香港', '台湾', '加拿大', '法国', '意大利', '泰国', '俄罗斯', '新西兰'],
        index: 60005,
    },
}


export const META_TAG: { [key: string]: MetaTagKind } = {
    书籍,
    动画,
    音乐,
    游戏,
    三次元,
}
